import { View, Text, StyleSheet, ScrollView, Pressable, Share, Alert, Linking } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
  User,
  Settings,
  Bell,
  Shield,
  FileText,
  Phone,
  LogOut,
  ChevronRight,
  Droplets,
  Calendar,
  Pill,
  Heart,
  Users,
  Share2,
  Download,
  Edit3,
  AlertTriangle,
  Globe,
  Eye,
  Lock,
  HelpCircle,
  Star,
} from 'lucide-react-native';
import Header from '@/components/Header';
import { usePatient } from '@/context/PatientContext';
import { colors, layout } from '@/constants/theme';
import { emergencyContacts, medications } from '@/constants/data';

export default function Profile() {
  const { patient, healthScore } = usePatient();

  const handleShareEmergencyCard = async () => {
    try {
      await Share.share({
        message: `EMERGENCY MEDICAL CARD

Name: ${patient.name}
Blood Type: ${patient.bloodType}
Diagnosis: ${patient.diagnosis}
Patient ID: ${patient.id}

IMPORTANT: This patient requires regular blood transfusions.

Medications:
- Deferasirox 500mg (Daily)
- Folic Acid 5mg (Daily)

Allergies: ${patient.allergies.length > 0 ? patient.allergies.join(', ') : 'None known'}

Emergency Contact: ${patient.emergencyContact.name} (${patient.emergencyContact.phone})
Primary Doctor: ${patient.primaryDoctor.name} (${patient.primaryDoctor.phone})

Generated by ThalassCare AI`,
      });
    } catch (error) {
      console.log('Error sharing:', error);
    }
  };

  const getHealthScoreColor = () => {
    if (healthScore >= 80) return colors.success;
    if (healthScore >= 60) return colors.warning;
    return colors.error;
  };

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <Header
        title="Profile"
        subtitle="Your Health Profile"
        icon={Settings}
      />

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Profile Card */}
        <View style={styles.profileCard}>
          <View style={styles.profileHeader}>
            <View style={styles.avatar}>
              <User size={32} color="#FFFFFF" />
            </View>
            <View style={styles.profileInfo}>
              <Text style={styles.userName}>{patient.name}</Text>
              <Text style={styles.patientId}>ID: {patient.id}</Text>
              <View style={styles.diagnosisBadge}>
                <Text style={styles.diagnosisText}>{patient.diagnosis}</Text>
              </View>
            </View>
            <Pressable style={styles.editButton} onPress={() => Alert.alert('Edit Profile', 'Profile editing will be available soon.')}>
              <Edit3 size={18} color={colors.primary} />
            </Pressable>
          </View>

          {/* Quick Stats */}
          <View style={styles.statsRow}>
            <View style={styles.statItem}>
              <View style={[styles.statIcon, { backgroundColor: '#FEE2E2' }]}>
                <Droplets size={16} color="#DC2626" />
              </View>
              <Text style={styles.statValue}>{patient.bloodType}</Text>
              <Text style={styles.statLabel}>Blood Type</Text>
            </View>
            <View style={styles.statDivider} />
            <View style={styles.statItem}>
              <View style={[styles.statIcon, { backgroundColor: getHealthScoreColor() + '20' }]}>
                <Heart size={16} color={getHealthScoreColor()} />
              </View>
              <Text style={[styles.statValue, { color: getHealthScoreColor() }]}>{healthScore}</Text>
              <Text style={styles.statLabel}>Health Score</Text>
            </View>
            <View style={styles.statDivider} />
            <View style={styles.statItem}>
              <View style={[styles.statIcon, { backgroundColor: '#DBEAFE' }]}>
                <Calendar size={16} color="#3B82F6" />
              </View>
              <Text style={styles.statValue}>{patient.age}</Text>
              <Text style={styles.statLabel}>Age</Text>
            </View>
          </View>
        </View>

        {/* Emergency Card */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Emergency Card</Text>
          <View style={styles.emergencyCard}>
            <View style={styles.emergencyCardHeader}>
              <View style={styles.emergencyIcon}>
                <AlertTriangle size={20} color="#DC2626" />
              </View>
              <View style={styles.emergencyHeaderInfo}>
                <Text style={styles.emergencyCardTitle}>Medical Emergency Card</Text>
                <Text style={styles.emergencyCardSubtitle}>Share with healthcare providers</Text>
              </View>
            </View>

            <View style={styles.emergencyDetails}>
              <View style={styles.emergencyRow}>
                <Text style={styles.emergencyLabel}>Blood Type</Text>
                <View style={styles.bloodTypeBadge}>
                  <Text style={styles.bloodTypeText}>{patient.bloodType}</Text>
                </View>
              </View>
              <View style={styles.emergencyRow}>
                <Text style={styles.emergencyLabel}>Condition</Text>
                <Text style={styles.emergencyValue}>{patient.diagnosis}</Text>
              </View>
              <View style={styles.emergencyRow}>
                <Text style={styles.emergencyLabel}>Allergies</Text>
                <Text style={styles.emergencyValue}>
                  {patient.allergies.length > 0 ? patient.allergies.join(', ') : 'None known'}
                </Text>
              </View>
              <View style={styles.emergencyRow}>
                <Text style={styles.emergencyLabel}>Emergency Contact</Text>
                <Text style={styles.emergencyValue}>{patient.emergencyContact.name}</Text>
              </View>
            </View>

            <View style={styles.emergencyActions}>
              <Pressable style={styles.shareButton} onPress={handleShareEmergencyCard}>
                <Share2 size={16} color="#FFFFFF" />
                <Text style={styles.shareButtonText}>Share</Text>
              </Pressable>
              <Pressable style={styles.downloadBtn} onPress={() => Alert.alert('Download', 'Emergency card saved to your device.')}>
                <Download size={16} color={colors.primary} />
                <Text style={styles.downloadBtnText}>Download</Text>
              </Pressable>
            </View>
          </View>
        </View>

        {/* Medical Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Medical Summary</Text>
          <View style={styles.summaryCard}>
            <View style={styles.summaryRow}>
              <View style={styles.summaryItem}>
                <Text style={styles.summaryLabel}>Diagnosed</Text>
                <Text style={styles.summaryValue}>{patient.diagnosisDate}</Text>
              </View>
              <View style={styles.summaryItem}>
                <Text style={styles.summaryLabel}>Primary Doctor</Text>
                <Text style={styles.summaryValue}>{patient.primaryDoctor.name}</Text>
              </View>
            </View>
            <View style={styles.summaryRow}>
              <View style={styles.summaryItem}>
                <Text style={styles.summaryLabel}>Hospital</Text>
                <Text style={styles.summaryValue}>{patient.primaryDoctor.hospital}</Text>
              </View>
              <View style={styles.summaryItem}>
                <Text style={styles.summaryLabel}>Transfusion Frequency</Text>
                <Text style={styles.summaryValue}>Every 3-4 weeks</Text>
              </View>
            </View>
          </View>
        </View>

        {/* Current Medications */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Current Medications</Text>
          <View style={styles.medsCard}>
            {medications.slice(0, 3).map(med => (
              <View key={med.id} style={styles.medItem}>
                <View style={[styles.medIcon, { backgroundColor: med.type === 'chelation' ? '#7C3AED20' : '#10B98120' }]}>
                  <Pill size={16} color={med.type === 'chelation' ? '#7C3AED' : '#10B981'} />
                </View>
                <View style={styles.medInfo}>
                  <Text style={styles.medName}>{med.name}</Text>
                  <Text style={styles.medDosage}>{med.dosage} • {med.frequency}</Text>
                </View>
              </View>
            ))}
          </View>
        </View>

        {/* Caregivers */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Caregivers</Text>
            <Pressable style={styles.addButton} onPress={() => Alert.alert('Add Caregiver', 'Add a new caregiver to your care team.')}>
              <Text style={styles.addButtonText}>+ Add</Text>
            </Pressable>
          </View>
          <View style={styles.caregiversCard}>
            <View style={styles.caregiverItem}>
              <View style={styles.caregiverAvatar}>
                <User size={18} color={colors.primary} />
              </View>
              <View style={styles.caregiverInfo}>
                <Text style={styles.caregiverName}>{patient.emergencyContact.name}</Text>
                <Text style={styles.caregiverRelation}>{patient.emergencyContact.relationship}</Text>
              </View>
              <Pressable style={styles.caregiverCall} onPress={() => Linking.openURL(`tel:${patient.emergencyContact.phone}`)}>
                <Phone size={16} color="#FFFFFF" />
              </Pressable>
            </View>
            <View style={styles.caregiverItem}>
              <View style={styles.caregiverAvatar}>
                <User size={18} color={colors.primary} />
              </View>
              <View style={styles.caregiverInfo}>
                <Text style={styles.caregiverName}>{patient.primaryDoctor.name}</Text>
                <Text style={styles.caregiverRelation}>Primary Doctor</Text>
              </View>
              <Pressable style={styles.caregiverCall} onPress={() => Linking.openURL(`tel:${patient.primaryDoctor.phone}`)}>
                <Phone size={16} color="#FFFFFF" />
              </Pressable>
            </View>
          </View>
        </View>

        {/* Settings Menu */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Settings</Text>
          <View style={styles.menuCard}>
            {[
              { icon: Bell, label: 'Notifications', color: '#F59E0B' },
              { icon: Globe, label: 'Language', color: '#3B82F6', value: 'English' },
              { icon: Eye, label: 'Accessibility', color: '#10B981' },
              { icon: Lock, label: 'Privacy & Security', color: '#8B5CF6' },
              { icon: FileText, label: 'Medical Records', color: '#EF4444' },
              { icon: HelpCircle, label: 'Help & Support', color: '#6B7280' },
            ].map((item, index) => (
              <Pressable key={index} style={styles.menuItem} onPress={() => Alert.alert(item.label, `${item.label} settings will open here.`)}>
                <View style={[styles.menuIcon, { backgroundColor: item.color + '15' }]}>
                  <item.icon size={18} color={item.color} />
                </View>
                <Text style={styles.menuText}>{item.label}</Text>
                {item.value && <Text style={styles.menuValue}>{item.value}</Text>}
                <ChevronRight size={18} color={colors.textMuted} />
              </Pressable>
            ))}
          </View>
        </View>

        {/* App Info */}
        <View style={styles.section}>
          <View style={styles.appInfoCard}>
            <View style={styles.appLogo}>
              <Heart size={24} color={colors.primary} />
            </View>
            <Text style={styles.appName}>ThalassCare AI</Text>
            <Text style={styles.appVersion}>Version 1.0.0</Text>
            <View style={styles.ratingRow}>
              {[1, 2, 3, 4, 5].map(i => (
                <Star key={i} size={16} color="#F59E0B" fill={i <= 4 ? '#F59E0B' : 'transparent'} />
              ))}
              <Text style={styles.ratingText}>Rate Us</Text>
            </View>
          </View>
        </View>

        {/* Sign Out */}
        <Pressable style={styles.signOutButton} onPress={() => Alert.alert('Sign Out', 'Are you sure you want to sign out?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign Out', style: 'destructive' }])}>
          <LogOut size={18} color="#DC2626" />
          <Text style={styles.signOutText}>Sign Out</Text>
        </Pressable>

        <Text style={styles.footerText}>
          Made with care for thalassemia patients
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: layout.scrollContentPadding,
  },
  section: {
    marginTop: 24,
    paddingHorizontal: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  addButton: {
    marginBottom: 12,
  },
  addButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  // Profile Card
  profileCard: {
    backgroundColor: colors.surface,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primaryDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfo: {
    flex: 1,
    marginLeft: 16,
  },
  userName: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  patientId: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 8,
  },
  diagnosisBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primary + '15',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  diagnosisText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  editButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.border,
  },
  // Emergency Card
  emergencyCard: {
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  emergencyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  emergencyIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emergencyHeaderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  emergencyCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#DC2626',
  },
  emergencyCardSubtitle: {
    fontSize: 13,
    color: '#7F1D1D',
    marginTop: 2,
  },
  emergencyDetails: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  emergencyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#FEE2E2',
  },
  emergencyLabel: {
    fontSize: 13,
    color: colors.textMuted,
  },
  emergencyValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  bloodTypeBadge: {
    backgroundColor: '#DC2626',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  bloodTypeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  emergencyActions: {
    flexDirection: 'row',
  },
  shareButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    paddingVertical: 12,
    borderRadius: 10,
    marginRight: 10,
  },
  shareButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 6,
  },
  downloadBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  downloadBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    marginLeft: 6,
  },
  // Summary Card
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 16,
  },
  summaryRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  summaryItem: {
    flex: 1,
  },
  summaryLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  // Medications
  medsCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 4,
  },
  medItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  medIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  medInfo: {
    flex: 1,
    marginLeft: 12,
  },
  medName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  medDosage: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  // Caregivers
  caregiversCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 4,
  },
  caregiverItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  caregiverAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primaryLight + '30',
    alignItems: 'center',
    justifyContent: 'center',
  },
  caregiverInfo: {
    flex: 1,
    marginLeft: 12,
  },
  caregiverName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  caregiverRelation: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  caregiverCall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Menu
  menuCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuText: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    marginLeft: 12,
  },
  menuValue: {
    fontSize: 14,
    color: colors.textMuted,
    marginRight: 8,
  },
  // App Info
  appInfoCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  appLogo: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.primaryLight + '30',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  appName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  appVersion: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 12,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
    marginLeft: 8,
  },
  // Sign Out
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    marginHorizontal: 20,
    marginTop: 24,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  signOutText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#DC2626',
    marginLeft: 8,
  },
  footerText: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 20,
  },
});
